# Auto-generated training data
TRAINING_EXAMPLES = [
    {'text': 'INSAT-3DR provides 0.1° X 0.1°', 'label': 1},
    {'text': 'INSAT-3D provides 0.1° X 0.1°', 'label': 1},
    {'text': 'SCATSAT-1 provides 0.1° X 0.1°', 'label': 1},
    {'text': 'SARAL provides 0.1° X 0.1°', 'label': 1},
    {'text': 'INSAT-3DR provides 1 hour', 'label': 1},
    {'text': 'INSAT-3D provides 1 hour', 'label': 1},
    {'text': 'SCATSAT-1 provides 1 hour', 'label': 1},
    {'text': 'SARAL provides 1 hour', 'label': 1},
    {'text': 'INSAT-3DR provides 1 km', 'label': 1},
    {'text': 'INSAT-3A\nINSAT-3A provides 1 km', 'label': 1},
    {'text': 'INSAT-3A provides 1 km', 'label': 1},
    {'text': 'INSAT-3D provides 1 km', 'label': 1},
    {'text': 'SCATSAT-1 provides 1 km', 'label': 1},
    {'text': 'SARAL provides 1 km', 'label': 1},
    {'text': 'INSAT-3DR provides 1 year', 'label': 1},
    {'text': 'INSAT-3D provides 1 year', 'label': 1},
    {'text': 'SCATSAT-1 provides 1 year', 'label': 1},
    {'text': 'SARAL provides 1 year', 'label': 1},
    {'text': 'INSAT-3DR provides 1 year ° March 2013 to February 2014', 'label': 1},
    {'text': 'INSAT-3D provides 1 year ° March 2013 to February 2014', 'label': 1},
    {'text': 'SCATSAT-1 provides 1 year ° March 2013 to February 2014', 'label': 1},
    {'text': 'SARAL provides 1 year ° March 2013 to February 2014', 'label': 1},
    {'text': 'INSAT-3DR provides 1611°1626', 'label': 1},
    {'text': 'INSAT-3D provides 1611°1626', 'label': 1},
    {'text': 'SCATSAT-1 provides 1611°1626', 'label': 1},
    {'text': 'SARAL provides 1611°1626', 'label': 1},
    {'text': 'INSAT-3DR provides 183.31GHz', 'label': 1},
    {'text': 'INSAT-3D provides 183.31GHz', 'label': 1},
    {'text': 'SCATSAT-1 provides 183.31GHz', 'label': 1},
    {'text': 'SARAL provides 183.31GHz', 'label': 1},
    {'text': 'INSAT-3DR provides 1993-2016', 'label': 1},
    {'text': 'INSAT-3D provides 1993-2016', 'label': 1},
    {'text': 'SCATSAT-1 provides 1993-2016', 'label': 1},
    {'text': 'SARAL provides 1993-2016', 'label': 1},
    {'text': 'INSAT-3DR provides 20.0 km', 'label': 1},
    {'text': 'INSAT-3D provides 20.0 km', 'label': 1},
    {'text': 'SCATSAT-1 provides 20.0 km', 'label': 1},
    {'text': 'SARAL provides 20.0 km', 'label': 1},
    {'text': 'INSAT-3DR provides 2002 - 2015', 'label': 1},
    {'text': 'INSAT-3D provides 2002 - 2015', 'label': 1},
    {'text': 'SCATSAT-1 provides 2002 - 2015', 'label': 1},
    {'text': 'SARAL provides 2002 - 2015', 'label': 1},
    {'text': 'INSAT-3DR provides 2007 - 2012', 'label': 1},
    {'text': 'INSAT-3D provides 2007 - 2012', 'label': 1},
    {'text': 'SCATSAT-1 provides 2007 - 2012', 'label': 1},
    {'text': 'SARAL provides 2007 - 2012', 'label': 1},
    {'text': 'INSAT-3DR provides 2008-2014', 'label': 1},
    {'text': 'SARAL/Altika provides 2008-2014', 'label': 1},
    {'text': 'INSAT-3D provides 2008-2014', 'label': 1},
    {'text': 'SCATSAT-1 provides 2008-2014', 'label': 1},
    {'text': 'SARAL provides 2008-2014', 'label': 1},
    {'text': 'INSAT-3DR provides 2008-2014\n15', 'label': 1},
    {'text': 'SARAL/Altika provides 2008-2014\n15', 'label': 1},
    {'text': 'INSAT-3D provides 2008-2014\n15', 'label': 1},
    {'text': 'SCATSAT-1 provides 2008-2014\n15', 'label': 1},
    {'text': 'SARAL provides 2008-2014\n15', 'label': 1},
    {'text': 'INSAT-3DR provides 2017-04-06 15:31', 'label': 1},
    {'text': 'INSAT-3D provides 2017-04-06 15:31', 'label': 1},
    {'text': 'SCATSAT-1 provides 2017-04-06 15:31', 'label': 1},
    {'text': 'SARAL provides 2017-04-06 15:31', 'label': 1},
    {'text': 'INSAT-3DR provides 228–231', 'label': 1},
    {'text': 'INSAT-3D provides 228–231', 'label': 1},
    {'text': 'SCATSAT-1 provides 228–231', 'label': 1},
    {'text': 'SARAL provides 228–231', 'label': 1},
    {'text': 'INSAT-3DR provides 23 years', 'label': 1},
    {'text': 'INSAT-3D provides 23 years', 'label': 1},
    {'text': 'SCATSAT-1 provides 23 years', 'label': 1},
    {'text': 'SARAL provides 23 years', 'label': 1},
    {'text': 'INSAT-3DR provides 24 years', 'label': 1},
    {'text': 'INSAT-3D provides 24 years', 'label': 1},
    {'text': 'SCATSAT-1 provides 24 years', 'label': 1},
    {'text': 'SARAL provides 24 years', 'label': 1},
    {'text': 'INSAT-3DR provides 25 February 2013', 'label': 1},
    {'text': 'SARAL/ provides 25 February 2013', 'label': 1},
    {'text': 'SARAL-Altika provides 25 February 2013', 'label': 1},
    {'text': 'INSAT-3D provides 25 February 2013', 'label': 1},
    {'text': 'SCATSAT-1 provides 25 February 2013', 'label': 1},
    {'text': 'SARAL provides 25 February 2013', 'label': 1},
    {'text': 'INSAT-3DR provides 25 km', 'label': 1},
    {'text': 'INSAT-3D provides 25 km', 'label': 1},
    {'text': 'SCATSAT-1 provides 25 km', 'label': 1},
    {'text': 'SARAL provides 25 km', 'label': 1},
    {'text': 'INSAT-3DR provides 2A/|f|', 'label': 1},
    {'text': 'INSAT-3D provides 2A/|f|', 'label': 1},
    {'text': 'SCATSAT-1 provides 2A/|f|', 'label': 1},
    {'text': 'SARAL provides 2A/|f|', 'label': 1},
    {'text': 'INSAT-3DR provides 3 days', 'label': 1},
    {'text': 'INSAT-3D provides 3 days', 'label': 1},
    {'text': 'SCATSAT-1 provides 3 days', 'label': 1},
    {'text': 'SARAL provides 3 days', 'label': 1},
    {'text': 'INSAT-3DR provides 3 days old', 'label': 1},
    {'text': 'INSAT-3D provides 3 days old', 'label': 1},
    {'text': 'SCATSAT-1 provides 3 days old', 'label': 1},
    {'text': 'SARAL provides 3 days old', 'label': 1},
    {'text': 'INSAT provides 310 mm', 'label': 1},
    {'text': 'INSAT-3DR provides 310 mm', 'label': 1},
    {'text': 'Kalpana-1 provides 310 mm', 'label': 1},
    {'text': 'INSAT-3D provides 310 mm', 'label': 1},
    {'text': 'SCATSAT-1 provides 310 mm', 'label': 1},
    {'text': 'SARAL provides 310 mm', 'label': 1},
    {'text': 'INSAT3DR-Sounder Feed provides Genetic Algorithm', 'label': 0},
    {'text': 'INSAT3DR-Imager Feed provides Genetic Algorithm', 'label': 0},
    {'text': 'INSAT-3A provides raw data', 'label': 0},
    {'text': 'INSAT-3DR provides Genetic Algorithm', 'label': 0},
    {'text': 'Kalpana-1 provides lanczos', 'label': 0},
    {'text': 'INSAT-3A\nINSAT-3A provides beta', 'label': 0},
    {'text': 'SARAL/ provides beta', 'label': 0},
    {'text': 'INSAT-3DR provides test', 'label': 0},
    {'text': 'INSAT3DR-Sounder Feed provides Genetic Algorithm', 'label': 0},
    {'text': 'The Megha-Tropiques provides Genetic Algorithm', 'label': 0},
    {'text': 'The Megha-Tropiques provides raw data', 'label': 0},
    {'text': 'Megha-Tropiques Microwave Sounder-SAPHIR provides lanczos', 'label': 0},
    {'text': 'INSAT-3A provides 40 Hz', 'label': 0},
    {'text': 'The Megha-Tropiques provides raw data', 'label': 0},
    {'text': 'Kalpana-1 provides lanczos', 'label': 0},
    {'text': 'INSAT-3A\nINSAT-3A provides lanczos', 'label': 0},
    {'text': 'INSAT3DR-Sounder Feed provides raw data', 'label': 0},
    {'text': 'Megha-Tropiques Microwave Sounder-SAPHIR provides beta', 'label': 0},
    {'text': 'INSAT-3DR provides v1.0', 'label': 0},
    {'text': 'SARAL provides lanczos', 'label': 0},
    {'text': 'SARAL-Altika provides v1.0', 'label': 0},
    {'text': 'Megha-Tropiques Microwave Sounder-SAPHIR provides test', 'label': 0},
    {'text': 'The Megha-Tropiques provides raw data', 'label': 0},
    {'text': 'The Megha-Tropiques provides beta', 'label': 0},
    {'text': 'SARAL/Altika provides Genetic Algorithm', 'label': 0},
    {'text': 'INSAT3DR provides 40 Hz', 'label': 0},
    {'text': 'SARAL provides test', 'label': 0},
    {'text': 'Megha-Tropiques Microwave Sounder-SAPHIR provides beta', 'label': 0},
    {'text': 'SARAL/ provides v1.0', 'label': 0},
    {'text': 'INSAT3DR-Imager Feed provides 40 Hz', 'label': 0},
    {'text': 'INSAT-3D provides 40 Hz', 'label': 0},
    {'text': 'INSAT-3A\nINSAT-3A provides beta', 'label': 0},
    {'text': 'INSAT-3DR provides raw data', 'label': 0},
    {'text': 'INSAT3DR provides raw data', 'label': 0},
    {'text': 'SARAL/ provides beta', 'label': 0},
    {'text': 'INSAT-3DR provides raw data', 'label': 0},
    {'text': 'INSAT3DR-Imager Feed provides beta', 'label': 0},
    {'text': 'SARAL/ provides beta', 'label': 0},
    {'text': 'INSAT-3DR provides v1.0', 'label': 0},
    {'text': 'INSAT-3DR provides beta', 'label': 0},
    {'text': 'INSAT-3D provides test', 'label': 0},
    {'text': 'INSAT3DR provides test', 'label': 0},
    {'text': 'INSAT provides 40 Hz', 'label': 0},
    {'text': 'Megha-Tropiques Microwave Sounder-SAPHIR provides Genetic Algorithm', 'label': 0},
    {'text': 'Megha-Tropiques Microwave Sounder-SAPHIR provides Genetic Algorithm', 'label': 0},
    {'text': 'SARAL-Altika provides raw data', 'label': 0},
    {'text': 'SARAL provides Genetic Algorithm', 'label': 0},
    {'text': 'INSAT-3D provides Genetic Algorithm', 'label': 0},
    {'text': 'SARAL provides raw data', 'label': 0},
    {'text': 'INSAT-3D provides test', 'label': 0},
    {'text': 'The Megha-Tropiques provides beta', 'label': 0},
    {'text': 'INSAT-3D provides v1.0', 'label': 0},
    {'text': 'SARAL/ provides raw data', 'label': 0},
    {'text': 'SCATSAT-1 provides test', 'label': 0},
    {'text': 'Megha-Tropiques Microwave Sounder-SAPHIR provides Genetic Algorithm', 'label': 0},
    {'text': 'SARAL provides Genetic Algorithm', 'label': 0},
    {'text': 'Megha-Tropiques Microwave Sounder-SAPHIR provides test', 'label': 0},
    {'text': 'Kalpana-1 provides 40 Hz', 'label': 0},
    {'text': 'SCATSAT-1 provides raw data', 'label': 0},
    {'text': 'SCATSAT-1 provides Genetic Algorithm', 'label': 0},
    {'text': 'INSAT-3A provides lanczos', 'label': 0},
    {'text': 'SCATSAT-1 provides Genetic Algorithm', 'label': 0},
    {'text': 'SARAL/ provides v1.0', 'label': 0},
    {'text': 'Kalpana-1 provides Genetic Algorithm', 'label': 0},
    {'text': 'SCATSAT-1 provides 40 Hz', 'label': 0},
    {'text': 'INSAT3DR-Sounder Feed provides test', 'label': 0},
    {'text': 'Kalpana-1 provides raw data', 'label': 0},
    {'text': 'Kalpana-1 provides 40 Hz', 'label': 0},
    {'text': 'INSAT3DR-Sounder Feed provides lanczos', 'label': 0},
    {'text': 'INSAT3DR-Imager Feed provides beta', 'label': 0},
    {'text': 'INSAT-3D provides v1.0', 'label': 0},
    {'text': 'SARAL/Altika provides 40 Hz', 'label': 0},
    {'text': 'INSAT provides test', 'label': 0},
    {'text': 'INSAT-3A provides lanczos', 'label': 0},
    {'text': 'INSAT3DR-Sounder Feed provides beta', 'label': 0},
    {'text': 'INSAT-3D provides v1.0', 'label': 0},
    {'text': 'SARAL/Altika provides raw data', 'label': 0},
    {'text': 'SARAL provides raw data', 'label': 0},
    {'text': 'INSAT-3D provides beta', 'label': 0},
    {'text': 'INSAT provides lanczos', 'label': 0},
    {'text': 'SARAL/ provides Genetic Algorithm', 'label': 0},
    {'text': 'SCATSAT-1 provides 40 Hz', 'label': 0},
    {'text': 'Kalpana-1 provides test', 'label': 0},
    {'text': 'INSAT-3A provides test', 'label': 0},
    {'text': 'Kalpana-1 provides v1.0', 'label': 0},
    {'text': 'Megha-Tropiques Microwave Sounder-SAPHIR provides 40 Hz', 'label': 0},
    {'text': 'INSAT-3A\nINSAT-3A provides lanczos', 'label': 0},
    {'text': 'SARAL/ provides test', 'label': 0},
    {'text': 'INSAT provides raw data', 'label': 0},
    {'text': 'SCATSAT-1 provides raw data', 'label': 0},
    {'text': 'INSAT3DR-Imager Feed provides Genetic Algorithm', 'label': 0},
    {'text': 'INSAT3DR-Imager Feed provides Genetic Algorithm', 'label': 0},
    {'text': 'INSAT3DR provides 40 Hz', 'label': 0},
    {'text': 'INSAT3DR-Sounder Feed provides v1.0', 'label': 0},
    {'text': 'SARAL/Altika provides test', 'label': 0},
    {'text': 'Kalpana-1 provides test', 'label': 0},
    {'text': 'SARAL/Altika provides raw data', 'label': 0},
    {'text': 'SARAL/Altika provides v1.0', 'label': 0},
    {'text': 'INSAT3DR-Imager Feed provides test', 'label': 0},
    {'text': 'SARAL/ provides Genetic Algorithm', 'label': 0},
]
